### PR TITLE
Grid component

### PR DESCRIPTION
**Pull request by shagunbagrecha**
CSS Grid:
 - 2 Column Grid
 - 3 Column Grid
 - 4 Column Grid

Preview: https://deploy-preview-7--vivid-ui.netlify.app/

### CODE REVIEW

**Review by someshtiwarii — APPROVED** [review]
good to go

**Review by kshitijthatte — APPROVED** [review]
In the 3 Column Grid, if there are more than 3 elements they are taking 4 columns instead of sticking to 3 columns.
The same is with 2 column grid, if there are more than 2 grid items it's not sticking to 2 columns.

**Comment by shagunbagrecha** [comment]
> In the 3 Column Grid, if there are more than 3 elements they are taking 4 columns instead of sticking to 3 columns. The same is with 2 column grid, if there are more than 2 grid items it's not sticking to 2 columns.

Hi @kshitijthatte,  modified it, have a look now!

**Comment by kshitijthatte** [comment]
> > In the 3 Column Grid, if there are more than 3 elements they are taking 4 columns instead of sticking to 3 columns. The same is with 2 column grid, if there are more than 2 grid items it's not sticking to 2 columns.
> 
> Hi @kshitijthatte, modified it, have a look now!

Looks good now!

**Pull request merged**
